{% set name = "napari-tyssue" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-tyssue-{{ version }}.tar.gz
  sha256: 24f453e2a418062770b6bc932f560481b0e9992499a0b0b031d9d036b39d39ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.10
  run:
    - imageio-ffmpeg
    - invagination >=0.0.2
    - magicgui
    - napari
    - numpy
    - pooch
    - pytables
    - python >=3.8,<3.10
    - qtpy
    - quantities
    - tyssue

test:
  imports:
    - napari_tyssue
  commands:
    - pip list
    # - pip check  # Fails due to invagination changed from == to >= 
  requires:
    - pip

about:
  home: https://github.com/kephale/napari-tyssue
  summary: A napari plugin for use with the tyssue library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - kephale
